# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20180625_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.User'),
        ),
    ]
