# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
        ('travels', '0003_auto_20180625_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='trip_members',
            field=models.ManyToManyField(related_name='joined_trips', to='login_register.User'),
        ),
    ]
