# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_auto_20180626_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='login_register.User'),
        ),
    ]
